import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createMockMcpServer } from "../src/lib/checkout/mcp-server";
import { createCheckoutService } from "../src/lib/checkout/service";
import { FileCheckoutRepository } from "../src/lib/checkout/repo";
import { DEMO_ADDRESS, DEMO_BUYER, DEMO_VARIANT_ID } from "../src/lib/checkout/fixtures";
import { PAYMENT_HANDLER_IDS, type CheckoutSession, type Order } from "../src/lib/checkout/contracts";

test("official MCP client discovers tools and completes catalog → checkout → order with REST-equivalent outputs", async t => {
  const dir = await mkdtemp(join(tmpdir(), "shopperzero-mcp-"));
  const service = createCheckoutService(new FileCheckoutRepository(join(dir, "data.json")));
  const server = createMockMcpServer(service);
  const client = new Client({ name: "mock-agent-test", version: "1" });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  t.after(async () => { await client.close(); await server.close(); await rm(dir, { recursive: true, force: true }); });
  await server.connect(serverTransport); await client.connect(clientTransport);
  const tools = (await client.listTools()).tools;
  assert.deepEqual(tools.map(t => t.name).sort(), ["cancel_checkout", "complete_checkout", "create_checkout", "get_checkout", "get_order", "get_product", "search_catalog", "update_checkout"]);
  assert.equal(tools.find(t => t.name === "complete_checkout")?.annotations?.destructiveHint, true);
  const catalog = await client.callTool({ name: "search_catalog", arguments: { query: "hoodie" } });
  assert.ok(Array.isArray((catalog.structuredContent as Record<string, unknown>)?.products));
  const product = await client.callTool({ name: "get_product", arguments: { id: DEMO_VARIANT_ID } });
  assert.equal((product.structuredContent as Record<string, unknown>)?.price, 4400);
  const created = await client.callTool({ name: "create_checkout", arguments: { checkout: { line_items: [{ item: { id: `sz:variant:${DEMO_VARIANT_ID}` }, quantity: 1 }] }, idempotency_key: "mcp-create" } });
  assert.ok(!created.isError);
  const checkout = created.structuredContent as unknown as CheckoutSession;
  assert.equal(checkout.state, "quoting");
  const updated = await client.callTool({ name: "update_checkout", arguments: { id: checkout.id, checkout: { buyer: DEMO_BUYER, fulfillment: { address: DEMO_ADDRESS } } } });
  assert.ok(!updated.isError, JSON.stringify(updated));
  assert.equal((updated.structuredContent as Record<string, unknown>)?.state, "awaiting_payment");
  const completeArgs = { id: checkout.id, checkout: { payment: { instruments: [{ handler_id: PAYMENT_HANDLER_IDS.stripe_spt, type: "card", credential: { type: "spt", token: "mock_card_visa" } }] }, idempotency_key: "mcp-complete" } };
  const completed = await client.callTool({ name: "complete_checkout", arguments: completeArgs });
  assert.ok(!completed.isError);
  const done = completed.structuredContent as unknown as CheckoutSession;
  assert.equal(done.state, "completed"); assert.ok(done.order);
  assert.deepEqual(done, await service.getCheckout(done.id));
  const repeated = await client.callTool({ name: "complete_checkout", arguments: completeArgs });
  assert.deepEqual(repeated.structuredContent, done);
  const order = await client.callTool({ name: "get_order", arguments: { id: done.order.id } });
  assert.deepEqual(order.structuredContent as unknown as Order, done.order);
  const get = await client.callTool({ name: "get_checkout", arguments: { id: done.id } });
  assert.deepEqual(get.structuredContent, done);
  const invalid = await client.callTool({ name: "cancel_checkout", arguments: { id: done.id } });
  assert.equal(invalid.isError, true);
});
